# Site settings
title: Valhalla.fr
email: your-email@domain.com
description: Sic Itur Ad Absurdum
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.valhalla.fr" # the base hostname & protocol for your site
twitter_username: valhallafr
github_username:  mw4rf
timezone: Europe/Paris

# Google Analytics ID
google_analytics: UA-2290016-1

# Build settings
markdown: kramdown

kramdown:
    parse_block_html: true
    input: GFM # GitHub Flavored Markdown
    hard_wrap: true # new lines => <br />
    smart_quotes: lsquo,rsquo,laquo,raquo #   ‘ ’  « » 

# Categories list
collections:
  category:
    output: true # creates a page per category
    permalink: /:collection/:name/index.html # e.g. /category/informatique/index.html

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category" # assign category.html layout to categories

# Exclude org-mode files from processing
exclude:
  - "*.org"

# Pagination
paginate: 5
paginate_path: "/archives/:num"

# Permalinks
permalink:     /:year/:month/:day/:title/

liquid:
  error_mode: lax # warn, strict

# Keywords
keywords:
  - Blog
  - Internet
  - Droit
  - Informatique
  - Vape
  - Actualité
  - Java
  - Juridique
  - Jurisprudence
  - Nouvelles technologies
  - NTIC
  - Société
  - Code
  - Tutoriel
  - Articles
  - Review
  - Veille

# Jekyll Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate