# Site settings
title: Valhalla.fr
email: your-email@domain.com
description: Ad Absurdum
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  mw4rf

# Build settings
markdown: kramdown

# Pagination
paginate: 10
paginate_path: "/archives/:num"

# Permalinks
permalink:     /:year/:month/:day/:title/