# Site settings
title: Valhalla.fr
email: your-email@domain.com
description: Ad Absurdum
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.valhalla.fr" # the base hostname & protocol for your site
twitter_username: valhallafr
github_username:  mw4rf

# GUI
bootswatch: yeti

# Google Analytics ID
google_analytics: UA-2290016-1

# Build settings
markdown: kramdown

# Pagination
paginate: 30
paginate_path: "/archives/:num"

# Permalinks
permalink:     /:year/:month/:day/:title/

# Jekyll Plugins
gems:
  - jekyll-sitemap