# Site settings
title: Valhalla.fr
email: your-email@domain.com
description: Ad Absurdum
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.valhalla.fr" # the base hostname & protocol for your site
twitter_username: valhallafr
github_username:  mw4rf
timezone: Europe/Paris

# GUI
bootswatch: yeti

# Google Analytics ID
google_analytics: UA-2290016-1

# Build settings
markdown: kramdown

kramdown:
    parse_block_html: true

# Exclude org-mode files from processing
exclude:
  - "*.org"

# Pagination
paginate: 30
paginate_path: "/archives/:num"

# Permalinks
permalink:     /:year/:month/:day/:title/

liquid:
  error_mode: lax # warn, strict

# Keywords
keywords:
  - Blog
  - Internet
  - Droit
  - Informatique
  - Vape
  - Actualité
  - Java
  - Juridique
  - Jurisprudence
  - Nouvelles technologies
  - NTIC
  - Société
  - Code
  - Tutoriel
  - Articles
  - Review
  - Veille

# Jekyll Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate